version: "3.8"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    networks:
      - BeeNetwork
    env_file:
      - qbittorrent.env
    volumes:
      - /srv/docker_data/qbittorrent/config:/config
      - /srv/docker_data/downloads:/downloads
    ports:
      - target: 6881
        published: 6881
        protocol: tcp
        mode: host
      - target: 6881
        published: 6881
        protocol: udp
        mode: host
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.qbittorrent.entrypoints=http"
        - "traefik.http.routers.qbittorrent.rule=Host(\"qbittorrent.local.nixit.it\")"
        - "traefik.http.middlewares.qbittorrent-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.qbittorrent.middlewares=qbittorrent-https-redirect"
        - "traefik.http.routers.qbittorrent-secure.entrypoints=https"
        - "traefik.http.routers.qbittorrent-secure.rule=Host(\"qbittorrent.local.nixit.it\")"
        - "traefik.http.routers.qbittorrent-secure.tls=true"
        - "traefik.http.routers.qbittorrent-secure.service=qbittorrent"
        - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"
        - "traefik.docker.network=BeeNetwork"
      placement:
        constraints: [node.hostname == storinator]
networks:
  BeeNetwork:
    external: true