version: "3.8"
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    networks:
      - BeeNetwork
    env_file:
      - prowlarr.env
    volumes:
      - /srv/docker_data/prowlarr:/config
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=BeeNetwork"
        - "traefik.http.routers.prowlarr.entrypoints=http"
        - "traefik.http.routers.prowlarr.rule=Host(\"prowlarr.local.nixit.it\")"
        - "traefik.http.middlewares.prowlarr-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.prowlarr.middlewares=prowlarr-https-redirect"
        - "traefik.http.routers.prowlarr-secure.entrypoints=https"
        - "traefik.http.routers.prowlarr-secure.rule=Host(\"prowlarr.local.nixit.it\")"
        - "traefik.http.routers.prowlarr-secure.tls=true"
        - "traefik.http.routers.prowlarr-secure.service=prowlarr"
        - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
      placement:
        constraints: [node.hostname == storinator]
networks:
  BeeNetwork:
    external: true