version: "3.8"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    networks:
      - BeeNetwork
    env_file:
      - radarr.env
    volumes:
      - /srv/docker_data/radarr:/config
      - /srv/docker_data/multimedia/movies:/movies
      - /srv/docker_data/downloads:/downloads
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.radarr.entrypoints=http"
        - "traefik.http.routers.radarr.rule=Host(\"radarr.local.nixit.it\")"
        - "traefik.http.middlewares.radarr-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.radarr.middlewares=radarr-https-redirect"
        - "traefik.http.routers.radarr-secure.entrypoints=https"
        - "traefik.http.routers.radarr-secure.rule=Host(\"radarr.local.nixit.it\")"
        - "traefik.http.routers.radarr-secure.tls=true"
        - "traefik.http.routers.radarr-secure.service=radarr"
        - "traefik.http.services.radarr.loadbalancer.server.port=7878"
        - "traefik.docker.network=BeeNetwork"
      placement:
        constraints: [node.hostname == storinator]
networks:
  BeeNetwork:
    external: true