version: "3.8"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    networks:
      - BeeNetwork
    env_file:
      - sonarr.env
    volumes:
      - /srv/docker_data/sonarr:/config
      - /srv/docker_data/multimedia/tv:/tv
      - /srv/docker_data/downloads:/downloads
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=-BeeNetwork"
        - "traefik.http.routers.sonarr.entrypoints=http"
        - "traefik.http.routers.sonarr.rule=Host(\"sonarr.local.nixit.it\")"
        - "traefik.http.middlewares.sonarr-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.sonarr.middlewares=sonarr-https-redirect"
        - "traefik.http.routers.sonarr-secure.entrypoints=https"
        - "traefik.http.routers.sonarr-secure.rule=Host(\"sonarr.local.nixit.it\")"
        - "traefik.http.routers.sonarr-secure.tls=true"
        - "traefik.http.routers.sonarr-secure.service=sonarr"
        - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
      placement:
        constraints: [node.hostname == storinator]
networks:
  BeeNetwork:
    external: true